name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Restore release configuration
      run: echo "${{ secrets.KEY }}" | base64 -di > app/astro_gallery.keystore
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean && ./gradlew assembleRelease
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
    - run: ls app/build/outputs
    - run: ls app/build/outputs/apk
    - run: ls app/build/outputs/apk/release
    - name: Install node and nvm
      uses: actions/setup-node@v2
      with:
        node-version: '16.9.1'
    - name: Install firebase-tools
      run: npm install -g firebase-tools
    - name: Publish to firebase
      run: firebase appdistribution:distribute --app 1:1098153219884:android:7b0ba4b4c9d6a51c323e89 --release-notes-file release-notes.txt --groups qa app/build/outputs/apk/release/app-release.apk --token 1//0g7-q3uSseEYSCgYIARAAGBASNwF-L9IryvYhiPFfAD1kP-8SaAhgUwq-imFU3AfwpbyCFvHgbpLzOmDoMTCNPhmXE7h7zln4vKg
