name: Training
on:
  workflow_dispatch:
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Install node and nvm
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - name: Install npm
        run: nvm install 16.9.1
      - name: Install firebase-tools
        run: ~/.nvm/versions/node/v16.9.0/bin/npm install -g firebase-tools
      - name: Publish to firebase
        run: firebase appdistribution:distribute --app 1:1098153219884:android:7b0ba4b4c9d6a51c323e89 --release-notes-file release-notes.txt --groups qa app/build/outputs/apk/release/app-release-unsigned.apk --token 1//0g7-q3uSseEYSCgYIARAAGBASNwF-L9IryvYhiPFfAD1kP-8SaAhgUwq-imFU3AfwpbyCFvHgbpLzOmDoMTCNPhmXE7h7zln4vKg