name: Training
on:
  push:
    branches: [ workflows ]
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: Message to display
        required: true
        default: "Hello World"
      channel:
        type: choice
        description: Send via
        required: true
        options:
          - mobile notification
          - email
          - slack
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print user message
        run: echo "Inside repository ${{ github.repository }}"
      - run: echo "${{ github.event.inputs.message }}"
      - run: ls ${{ github.workspace }}