name: Training
on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        description: Message to display
        required: true
        default: "Hello World"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print user message
        run: echo ${{ inputs.message }}